'use client';

import Link from 'next/link';
import { useEffect } from 'react';
import { useLang } from '@/lib/useLang';

const content = {
  ko: {
    back: '← 홈으로',
    title: '이용약관',
    lastUpdated: '최종 수정일: 2026년 4월 5일',
    sections: [
      { title: '제1조 (목적)', body: '본 약관은 오늘의 운세(이하 "서비스")가 제공하는 운세 서비스의 이용 조건 및 절차, 서비스 이용자와 서비스 간의 권리·의무 및 책임사항을 규정함을 목적으로 합니다.' },
      { title: '제2조 (서비스 내용)', body: '서비스는 이용자가 입력한 생년월일을 기반으로 별자리·띠를 계산하고, AI를 활용하여 오늘의 운세를 생성하여 제공합니다. 운세는 오락·참고 목적으로만 제공되며 어떠한 법적 책임도 지지 않습니다.' },
      { title: '제3조 (면책 조항)', body: '서비스가 제공하는 운세 정보는 AI가 생성한 오락적 콘텐츠로, 실제 미래를 예측하거나 보장하지 않습니다. 운세 정보를 근거로 한 이용자의 결정 및 행동에 대해 서비스는 책임을 지지 않습니다. 서비스는 천재지변, 시스템 장애 등 불가항력적 사유로 인한 서비스 중단에 대해 책임을 지지 않습니다.' },
      { title: '제4조 (광고)', body: '서비스는 Google AdSense 등 제3자 광고 네트워크를 통해 광고를 게재할 수 있습니다. 광고 콘텐츠는 광고주의 책임 하에 제공되며, 서비스는 광고 내용에 대해 책임을 지지 않습니다.' },
      { title: '제5조 (저작권)', body: '서비스가 생성한 운세 콘텐츠의 저작권은 서비스에 귀속됩니다. 이용자는 개인적인 용도로 공유할 수 있으나, 상업적 목적으로 무단 복제·배포하는 행위는 금지됩니다.' },
      { title: '제6조 (약관 변경)', body: '서비스는 필요한 경우 본 약관을 변경할 수 있으며, 변경된 약관은 사이트 내 공지를 통해 효력이 발생합니다.' },
      { title: '제7조 (준거법)', body: '본 약관은 대한민국 법령에 따라 해석되며, 서비스 이용과 관련한 분쟁은 대한민국 법원을 관할로 합니다.' },
    ],
  },
  en: {
    back: '← Back to Home',
    title: 'Terms of Service',
    lastUpdated: 'Last updated: April 5, 2026',
    sections: [
      { title: 'Article 1 (Purpose)', body: 'These Terms govern the conditions and procedures for using the Fortune Teller service (hereinafter "Service"), and define the rights, obligations, and responsibilities between users and the Service.' },
      { title: 'Article 2 (Service Description)', body: 'The Service calculates your zodiac sign and Chinese zodiac based on your birth date, and uses AI to generate your daily fortune. Fortunes are provided for entertainment and reference purposes only; the Service bears no legal liability.' },
      { title: 'Article 3 (Disclaimer)', body: 'The fortune information provided by the Service is AI-generated entertainment content and does not predict or guarantee actual future events. The Service is not responsible for any decisions or actions taken by users based on fortune information. The Service is not liable for service interruptions caused by force majeure events such as natural disasters or system failures.' },
      { title: 'Article 4 (Advertising)', body: 'The Service may display advertisements through third-party ad networks such as Google AdSense. Ad content is the responsibility of advertisers, and the Service is not liable for ad content.' },
      { title: 'Article 5 (Copyright)', body: 'The copyright of fortune content generated by the Service belongs to the Service. Users may share content for personal use, but unauthorized reproduction or distribution for commercial purposes is prohibited.' },
      { title: 'Article 6 (Changes to Terms)', body: 'The Service may update these Terms as necessary. Changes take effect upon notice posted on the site.' },
      { title: 'Article 7 (Governing Law)', body: 'These Terms are governed by the laws of the Republic of Korea. Disputes related to the use of the Service shall be subject to the jurisdiction of Korean courts.' },
    ],
  },
  zh: {
    back: '← 返回首页',
    title: '使用条款',
    lastUpdated: '最后更新：2026年4月5日',
    sections: [
      { title: '第1条（目的）', body: '本条款规定了今日运势（以下简称"服务"）提供的运势服务的使用条件及程序，以及用户与服务之间的权利、义务和责任事项。' },
      { title: '第2条（服务内容）', body: '服务根据用户输入的生日计算星座和生肖，并利用AI生成今日运势。运势仅供娱乐和参考目的提供，服务不承担任何法律责任。' },
      { title: '第3条（免责声明）', body: '服务提供的运势信息是AI生成的娱乐内容，不预测或保证实际未来事件。服务对用户基于运势信息做出的决定和行动不承担责任。服务对因自然灾害、系统故障等不可抗力原因导致的服务中断不承担责任。' },
      { title: '第4条（广告）', body: '服务可能通过Google AdSense等第三方广告网络投放广告。广告内容由广告主负责，服务不对广告内容承担责任。' },
      { title: '第5条（版权）', body: '服务生成的运势内容的版权归服务所有。用户可以出于个人目的分享，但禁止未经授权出于商业目的复制或分发。' },
      { title: '第6条（条款变更）', body: '服务可根据需要修改本条款，修改后的条款通过网站公告生效。' },
      { title: '第7条（适用法律）', body: '本条款依据大韩民国法律解释，与服务使用相关的争议以韩国法院为管辖法院。' },
    ],
  },
  ja: {
    back: '← ホームへ',
    title: '利用規約',
    lastUpdated: '最終更新日：2026年4月5日',
    sections: [
      { title: '第1条（目的）', body: '本規約は、今日の運勢（以下「サービス」）が提供する運勢サービスの利用条件および手続き、サービス利用者とサービス間の権利・義務および責任事項を規定することを目的とします。' },
      { title: '第2条（サービス内容）', body: 'サービスは、ユーザーが入力した生年月日をもとに星座・干支を計算し、AIを活用して今日の運勢を生成して提供します。運勢はエンターテインメント・参考目的のみで提供され、いかなる法的責任も負いません。' },
      { title: '第3条（免責事項）', body: 'サービスが提供する運勢情報はAIが生成したエンタメコンテンツであり、実際の未来を予測または保証するものではありません。運勢情報を根拠としたユーザーの決断および行動についてサービスは責任を負いません。天災、システム障害等の不可抗力による サービス中断についてサービスは責任を負いません。' },
      { title: '第4条（広告）', body: 'サービスはGoogle AdSense等の第三者広告ネットワークを通じて広告を掲載する場合があります。広告コンテンツは広告主の責任のもとに提供され、サービスは広告内容に対して責任を負いません。' },
      { title: '第5条（著作権）', body: 'サービスが生成した運勢コンテンツの著作権はサービスに帰属します。ユーザーは個人的な目的で共有することができますが、商業目的での無断複製・配布は禁止されています。' },
      { title: '第6条（規約の変更）', body: 'サービスは必要に応じて本規約を変更することができ、変更された規約はサイト内告知により効力が生じます。' },
      { title: '第7条（準拠法）', body: '本規約は大韓民国の法令に従って解釈され、サービス利用に関する紛争は韓国の裁判所を管轄とします。' },
    ],
  },
};

const siteName = { ko: '오늘의 운세', en: 'Fortune Teller', zh: '今日运势', ja: '今日の運勢' };

export default function TermsPage() {
  const { lang } = useLang();
  const c = content[lang];

  useEffect(() => {
    document.title = `${c.title} | ${siteName[lang]}`;
  }, [lang, c.title]);

  return (
    <div style={{ background: 'linear-gradient(160deg, #050520 0%, #0a0a2e 30%, #130a2e 60%, #1a0a3e 100%)', minHeight: '100vh' }}>
      <div className="max-w-3xl mx-auto px-6 py-16 text-white/80">
        <Link href="/" className="text-purple-400 hover:text-purple-300 text-sm mb-8 inline-block">{c.back}</Link>
        <h1 className="text-3xl font-bold text-white mb-2">{c.title}</h1>
        <p className="text-white/40 text-sm mb-10">{c.lastUpdated}</p>
        <div className="space-y-10 text-sm leading-relaxed">
          {c.sections.map((section, i) => (
            <section key={i}>
              <h2 className="text-lg font-semibold text-white mb-3">{section.title}</h2>
              <p>{section.body}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
