import type { Lang } from './i18n';

export interface ChineseZodiacEntry {
  traits: string[];
  personality: string;
  strengths: string;
  weaknesses: string;
  compatible: string;
  careers: string;
}

export const CHINESE_ZODIAC_CONTENT: Record<Lang, ChineseZodiacEntry[]> = {
  ko: [
    { traits: ['영리하고 재치 있음', '적응력이 뛰어남', '호기심이 많음', '절약적'], personality: '쥐띠는 십이지 중 첫 번째로, 영리하고 재치 있는 성격을 가집니다. 새로운 환경에 빠르게 적응하는 능력이 뛰어나며, 관찰력이 날카롭습니다. 기회를 잘 포착하고 실용적인 사고를 갖고 있습니다.', strengths: '영리함, 적응력, 사교성, 실용적 사고', weaknesses: '때로 이기적, 소심함, 투기적 성향', compatible: '소띠, 용띠', careers: '비즈니스, 금융, 언론, 정치' },
    { traits: ['성실하고 근면함', '강한 의지와 인내', '신뢰할 수 있음', '보수적이고 전통적'], personality: '소띠는 성실하고 근면한 성격으로 유명합니다. 한 번 맡은 일은 끝까지 해내는 강한 책임감을 가지고 있습니다. 말보다는 행동으로 보여주는 타입이며, 약속을 매우 중요하게 여깁니다.', strengths: '성실함, 신뢰성, 인내심, 결단력', weaknesses: '고집스러움, 변화에 대한 저항, 완고함', compatible: '쥐띠, 뱀띠', careers: '농업, 건축, 의학, 교육, 군사' },
    { traits: ['용감하고 자신감 넘침', '카리스마 있는 리더십', '경쟁적이고 야망 있음', '독립적'], personality: '호랑이띠는 용감하고 열정적인 자연의 지도자입니다. 강한 자신감과 카리스마로 자연스럽게 주목을 받습니다. 불의를 보면 참지 못하는 정의감과, 약자를 돕는 따뜻한 마음도 가지고 있습니다.', strengths: '용기, 카리스마, 추진력, 관대함', weaknesses: '충동적, 반항적, 성급함', compatible: '말띠, 개띠', careers: '군인, 소방관, 사업가, 정치인, 운동선수' },
    { traits: ['온화하고 우아함', '예술적 감각이 뛰어남', '평화를 사랑함', '신중하고 조심스러움'], personality: '토끼띠는 십이지 중 가장 운이 좋은 동물 중 하나로 여겨집니다. 온화하고 우아한 성격으로 주변 사람들에게 사랑받습니다. 예술적 감각이 뛰어나고, 갈등을 싫어하고 평화로운 환경을 선호합니다.', strengths: '우아함, 외교술, 예술성, 세심함', weaknesses: '지나치게 신중함, 우유부단, 표면적인 관계', compatible: '양띠, 돼지띠', careers: '예술, 외교, 건강 관련 직종, 패션' },
    { traits: ['힘 있고 카리스마 넘침', '자신감 있고 열정적', '성공 지향적', '창의적이고 지적'], personality: '용띠는 십이지 중 유일한 신화적 동물로, 가장 강력한 에너지를 가집니다. 타고난 리더십과 카리스마로 어디서든 눈에 띄며, 성공을 향한 열망이 넘칩니다. 독립심이 강하고 자신만의 방식을 고집합니다.', strengths: '리더십, 열정, 창의성, 자신감', weaknesses: '오만할 수 있음, 완벽주의, 고집스러움', compatible: '쥐띠, 원숭이띠', careers: 'CEO, 예술가, 정치인, 건축가' },
    { traits: ['지혜롭고 직관적', '신중하고 사려 깊음', '우아하고 매력적', '철학적 사고'], personality: '뱀띠는 지혜와 직관이 뛰어난 별자리입니다. 깊이 생각하고 신중하게 행동하며, 직관적으로 상황을 파악하는 능력이 있습니다. 우아하고 신비로운 매력이 있어 사람들을 끌어당깁니다.', strengths: '지혜, 직관, 우아함, 분석력', weaknesses: '의심이 많음, 게으를 수 있음, 소유욕', compatible: '소띠, 닭띠', careers: '철학자, 작가, 심리학자, 교사, 점성가' },
    { traits: ['활동적이고 자유롭움', '열정적이고 에너지 넘침', '독립적이고 여행을 좋아함', '표현력이 풍부'], personality: '말띠는 자유롭고 활동적인 정신을 가진 별자리입니다. 광활한 초원을 달리는 말처럼, 자유와 독립을 갈망합니다. 열정적이고 에너지 넘치며, 새로운 환경과 경험을 즐깁니다.', strengths: '활동력, 자유로운 정신, 표현력, 독립성', weaknesses: '인내심 부족, 이기적일 수 있음, 결정 어려움', compatible: '호랑이띠, 양띠', careers: '운동선수, 여행가, 세일즈맨, 언론인' },
    { traits: ['창의적이고 예술적', '온화하고 친절함', '공감 능력이 뛰어남', '낭만적'], personality: '양띠는 온화하고 예술적인 감성을 가진 별자리입니다. 창의적인 재능과 미적 감각이 뛰어나며, 아름다운 것을 만들고 감상하는 것을 좋아합니다. 타인에 대한 깊은 공감과 이해심을 가지고 있습니다.', strengths: '창의성, 온화함, 공감 능력, 예술성', weaknesses: '지나치게 의존적, 우유부단, 걱정이 많음', compatible: '토끼띠, 돼지띠', careers: '예술가, 음악가, 디자이너, 상담사' },
    { traits: ['영리하고 재치 있음', '호기심 많고 장난기 있음', '빠른 학습 능력', '창의적 문제 해결'], personality: '원숭이띠는 십이지 중 가장 영리하고 재치 있는 별자리입니다. 빠른 사고력과 뛰어난 문제 해결 능력을 가지고 있으며, 새로운 것을 배우는 속도가 빠릅니다. 유머 감각이 뛰어나고, 어떤 상황에서도 긍정적인 면을 찾습니다.', strengths: '지능, 재치, 적응력, 문제 해결 능력', weaknesses: '무책임할 수 있음, 규율 부족, 부정직할 수 있음', compatible: '용띠, 쥐띠', careers: '과학자, 엔지니어, 작가, 배우, 외교관' },
    { traits: ['근면하고 꼼꼼함', '솔직하고 자신감 있음', '완벽주의 성향', '관찰력이 뛰어남'], personality: '닭띠는 근면하고 부지런한 성격으로 유명합니다. 매우 꼼꼼하고 세심하며, 맡은 일을 완벽하게 해내려는 완벽주의 성향이 있습니다. 솔직하고 직접적인 소통을 선호하며, 높은 자존감을 가지고 있습니다.', strengths: '근면성, 꼼꼼함, 솔직함, 자신감', weaknesses: '비판적, 완벽주의로 인한 스트레스, 지나친 자만', compatible: '소띠, 뱀띠', careers: '군인, 외과 의사, 치과 의사, 세프, 배우' },
    { traits: ['충실하고 신의가 있음', '공정하고 정의로움', '보호 본능이 강함', '헌신적'], personality: '개띠는 충성심과 신의를 가장 중요하게 여기는 별자리입니다. 한 번 믿음을 준 사람에게는 끝까지 함께하며, 불의를 보면 참지 못하는 강한 정의감을 가집니다. 소중한 사람들을 보호하려는 본능이 강합니다.', strengths: '충성심, 성실함, 정의감, 신뢰성', weaknesses: '걱정이 많음, 지나치게 비판적, 완고함', compatible: '호랑이띠, 말띠', careers: '경찰관, 사회복지사, 군인, 교사, 판사' },
    { traits: ['온화하고 관대함', '성실하고 순수함', '즐거움을 추구함', '결단력 있음'], personality: '돼지띠는 순수하고 관대한 마음을 가진 별자리입니다. 타인에 대한 강한 신뢰와 낙관적인 세계관을 가지며, 인생의 즐거움을 충분히 누리는 것을 믿습니다. 성실하고 책임감이 있어 맡은 일을 끝까지 완수합니다.', strengths: '관대함, 성실함, 낙관성, 순수함', weaknesses: '지나치게 신뢰, 물질적 탐닉, 고집스러움', compatible: '토끼띠, 양띠', careers: '의사, 연구원, 엔터테이너, 서비스 업종' },
  ],

  en: [
    { traits: ['Clever and witty', 'Highly adaptable', 'Very curious', 'Frugal and resourceful'], personality: 'The Rat is the first of the twelve zodiac signs, known for being clever and quick-witted. They adapt swiftly to new environments and have a sharp, observant eye. They are skilled at seizing opportunities and have a practical mindset.', strengths: 'Intelligence, adaptability, sociability, practical thinking', weaknesses: 'Can be self-centered, timid, speculative tendencies', compatible: 'Ox, Dragon', careers: 'Business, finance, journalism, politics' },
    { traits: ['Diligent and hardworking', 'Strong will and patience', 'Trustworthy and reliable', 'Conservative and traditional'], personality: 'The Ox is famous for being diligent and hardworking. Once they take on a task, they see it through with strong responsibility. They show more through actions than words and place great importance on keeping promises.', strengths: 'Diligence, reliability, patience, decisiveness', weaknesses: 'Stubborn, resistant to change, inflexible', compatible: 'Rat, Snake', careers: 'Agriculture, construction, medicine, education, military' },
    { traits: ['Brave and confident', 'Charismatic leader', 'Competitive and ambitious', 'Independent'], personality: 'The Tiger is a brave and passionate natural leader. Their strong confidence and charisma naturally draw attention. They have a strong sense of justice that cannot ignore wrongdoing, and a warm heart that wants to help the vulnerable.', strengths: 'Courage, charisma, drive, generosity', weaknesses: 'Impulsive, rebellious, hot-headed', compatible: 'Horse, Dog', careers: 'Military, firefighter, entrepreneur, politician, athlete' },
    { traits: ['Gentle and elegant', 'Excellent artistic sense', 'Peace-loving', 'Careful and cautious'], personality: 'The Rabbit is considered one of the luckiest signs in the zodiac. Their gentle and elegant nature makes them well-loved by those around them. They have outstanding artistic sensibility and prefer a peaceful environment, avoiding conflict.', strengths: 'Elegance, diplomacy, artistry, attentiveness', weaknesses: 'Overly cautious, indecisive, superficial relationships', compatible: 'Goat, Pig', careers: 'Arts, diplomacy, healthcare, fashion' },
    { traits: ['Powerful and charismatic', 'Confident and passionate', 'Success-oriented', 'Creative and intelligent'], personality: 'The Dragon is the only mythological creature in the twelve zodiac signs, possessing the most powerful energy. Their natural leadership and charisma make them stand out anywhere, and their desire for success is boundless. They are fiercely independent and insist on doing things their own way.', strengths: 'Leadership, passion, creativity, confidence', weaknesses: 'Can be arrogant, perfectionist, stubborn', compatible: 'Rat, Monkey', careers: 'CEO, artist, politician, architect' },
    { traits: ['Wise and intuitive', 'Careful and thoughtful', 'Elegant and charming', 'Philosophical thinking'], personality: 'The Snake is a sign of great wisdom and intuition. They think deeply and act carefully, with an innate ability to read situations intuitively. Their elegant and mysterious charm draws people to them.', strengths: 'Wisdom, intuition, elegance, analytical ability', weaknesses: 'Suspicious, can be lazy, possessive', compatible: 'Ox, Rooster', careers: 'Philosopher, writer, psychologist, teacher, astrologer' },
    { traits: ['Active and free-spirited', 'Passionate and energetic', 'Independent, loves to travel', 'Expressive'], personality: 'The Horse is a sign with a free and active spirit. Like a horse galloping across an open prairie, they crave freedom and independence. They are passionate and full of energy, and they love new environments and experiences.', strengths: 'Energy, free spirit, expressiveness, independence', weaknesses: 'Impatient, can be self-centered, struggles with decisions', compatible: 'Tiger, Goat', careers: 'Athlete, traveler, salesperson, journalist' },
    { traits: ['Creative and artistic', 'Gentle and kind', 'Excellent empathy', 'Romantic'], personality: 'The Goat is a sign of gentle and artistic sensibility. They have outstanding creative talent and aesthetic sense, loving to create and appreciate beautiful things. They have a deep empathy and understanding for others.', strengths: 'Creativity, gentleness, empathy, artistry', weaknesses: 'Overly dependent, indecisive, worries too much', compatible: 'Rabbit, Pig', careers: 'Artist, musician, designer, counselor' },
    { traits: ['Clever and witty', 'Curious and playful', 'Fast learner', 'Creative problem-solver'], personality: 'The Monkey is the cleverest and most quick-witted sign of the twelve. They have rapid thinking and excellent problem-solving ability, and learn new things at a remarkable speed. Their great sense of humor helps them find the positive in any situation.', strengths: 'Intelligence, wit, adaptability, problem-solving', weaknesses: 'Can be irresponsible, lacks discipline, can be dishonest', compatible: 'Dragon, Rat', careers: 'Scientist, engineer, writer, actor, diplomat' },
    { traits: ['Hardworking and meticulous', 'Frank and confident', 'Perfectionist tendencies', 'Sharp observer'], personality: 'The Rooster is known for being hardworking and diligent. They are extremely meticulous and detail-oriented, with a perfectionist drive to execute tasks flawlessly. They prefer direct and honest communication and have high self-esteem.', strengths: 'Work ethic, meticulousness, frankness, confidence', weaknesses: 'Critical, stressed by perfectionism, overconfident', compatible: 'Ox, Snake', careers: 'Military, surgeon, dentist, chef, actor' },
    { traits: ['Loyal and faithful', 'Fair and just', 'Strong protective instinct', 'Devoted'], personality: 'The Dog places loyalty and faithfulness above all else. Once they give their trust to someone, they stand by them to the end. They have a strong sense of justice they cannot suppress when they witness wrongdoing. Their instinct to protect those they cherish is powerful.', strengths: 'Loyalty, diligence, sense of justice, reliability', weaknesses: 'Worries a lot, overly critical, inflexible', compatible: 'Tiger, Horse', careers: 'Police officer, social worker, military, teacher, judge' },
    { traits: ['Gentle and generous', 'Diligent and pure-hearted', 'Pursues joy and pleasure', 'Decisive'], personality: 'The Pig has a pure and generous heart. They have great trust in others and an optimistic worldview, believing in enjoying the good things in life to the fullest. They are diligent and responsible, always completing what they commit to.', strengths: 'Generosity, diligence, optimism, purity', weaknesses: 'Too trusting, prone to material indulgence, stubborn', compatible: 'Rabbit, Goat', careers: 'Doctor, researcher, entertainer, service industry' },
  ],

  zh: [
    { traits: ['聪明机灵', '适应力强', '好奇心旺盛', '节俭有方'], personality: '鼠是十二生肖中的第一位，以聪明机灵著称。他们能迅速适应新环境，观察力敏锐，善于抓住机遇，思维务实。', strengths: '聪明、适应力、社交能力、务实思维', weaknesses: '有时自私、胆小、有投机倾向', compatible: '牛、龙', careers: '商业、金融、新闻、政治' },
    { traits: ['踏实勤奋', '意志坚定，有耐心', '值得信赖', '保守传统'], personality: '牛以踏实勤奋著称。一旦承担工作，就会以强烈的责任感坚持到底。他们更注重行动而非言语，对承诺极为重视。', strengths: '勤奋、可靠、耐心、决断力', weaknesses: '固执、抵制变化、顽固', compatible: '鼠、蛇', careers: '农业、建筑、医学、教育、军事' },
    { traits: ['勇敢自信', '魅力领导力', '竞争意识强，有抱负', '独立自主'], personality: '虎是勇敢热情的天生领袖。强烈的自信和魅力自然引人注目。他们有着不能容忍不公正的正义感，也有着帮助弱者的温暖之心。', strengths: '勇气、魅力、推进力、慷慨', weaknesses: '冲动、叛逆、急躁', compatible: '马、狗', careers: '军人、消防员、企业家、政治家、运动员' },
    { traits: ['温和优雅', '艺术感强', '热爱和平', '谨慎细心'], personality: '兔被视为十二生肖中最幸运的动物之一。温和优雅的性格使其深受周围人喜爱。艺术感独特，厌恶冲突，偏爱平和的环境。', strengths: '优雅、外交手腕、艺术性、细心', weaknesses: '过于谨慎、优柔寡断、关系流于表面', compatible: '羊、猪', careers: '艺术、外交、医疗、时尚' },
    { traits: ['威猛且魅力十足', '自信热情', '以成功为导向', '富有创意，才智过人'], personality: '龙是十二生肖中唯一的神话动物，拥有最强大的能量。天生的领导力和魅力使其在任何地方都引人注目，对成功的渴望无边无际。独立性强，坚持己见。', strengths: '领导力、热情、创造力、自信', weaknesses: '可能傲慢、完美主义、固执', compatible: '鼠、猴', careers: '总裁、艺术家、政治家、建筑师' },
    { traits: ['智慧且直觉强', '谨慎深思熟虑', '优雅有魅力', '哲学思维'], personality: '蛇是智慧与直觉的象征。他们深思熟虑，行事谨慎，拥有凭直觉洞察局势的能力。优雅而神秘的魅力令人着迷。', strengths: '智慧、直觉、优雅、分析力', weaknesses: '多疑、有时懒散、占有欲强', compatible: '牛、鸡', careers: '哲学家、作家、心理学家、教师、占星师' },
    { traits: ['活泼自由', '热情活力充沛', '独立，爱旅行', '表达力强'], personality: '马是自由活泼的星座。如同驰骋草原的马儿，渴望自由与独立。热情洋溢，充满活力，热爱新环境和新体验。', strengths: '活力、自由精神、表达力、独立性', weaknesses: '缺乏耐心、有时自私、难以做决定', compatible: '虎、羊', careers: '运动员、旅行家、销售员、新闻工作者' },
    { traits: ['富有创意，艺术气质', '温和善良', '共情能力强', '浪漫'], personality: '羊是温柔而富有艺术气息的星座。创意才能与审美感出众，热爱创造和欣赏美好事物。对他人有着深厚的共情与理解。', strengths: '创造力、温和、共情能力、艺术性', weaknesses: '过于依赖他人、优柔寡断、多虑', compatible: '兔、猪', careers: '艺术家、音乐家、设计师、咨询师' },
    { traits: ['聪明机灵', '好奇心强，爱玩耍', '学习能力强', '擅长创意解决问题'], personality: '猴是十二生肖中最聪明机灵的星座。思维敏捷，问题解决能力出众，学习新事物速度极快。幽默感强，能在任何处境中发现积极的一面。', strengths: '智慧、机智、适应力、解决问题能力', weaknesses: '可能不负责任、缺乏纪律性、有时不诚实', compatible: '龙、鼠', careers: '科学家、工程师、作家、演员、外交官' },
    { traits: ['勤劳细心', '坦诚自信', '完美主义倾向', '观察力敏锐'], personality: '鸡以勤劳努力著称。极其细心周到，有着将工作做到完美的完美主义倾向。偏好直接坦诚的沟通方式，自尊心强。', strengths: '勤奋、细心、坦诚、自信', weaknesses: '爱批评、因完美主义而有压力、有时过于自大', compatible: '牛、蛇', careers: '军人、外科医生、牙医、厨师、演员' },
    { traits: ['忠诚守信', '公正正义', '保护本能强', '忠心耿耿'], personality: '狗最看重忠诚与信义。一旦给予信任，就会始终相伴。有着强烈的正义感，无法容忍不公之事。保护所爱之人的本能极强。', strengths: '忠诚、诚实、正义感、可靠性', weaknesses: '多虑、过于挑剔、固执', compatible: '虎、马', careers: '警察、社会工作者、军人、教师、法官' },
    { traits: ['温和慷慨', '勤奋纯真', '追求快乐', '果断有力'], personality: '猪拥有纯真慷慨的心。对他人有强烈的信任感和乐观的世界观，相信充分享受生活的美好。勤奋负责，凡是承诺的事情都会坚持完成。', strengths: '慷慨、勤奋、乐观、纯真', weaknesses: '过于轻信他人、沉溺于物质享受、固执', compatible: '兔、羊', careers: '医生、研究员、艺人、服务业' },
  ],

  ja: [
    { traits: ['賢くて機知に富む', '適応力が高い', '好奇心旺盛', '倹約家'], personality: '子（ねずみ）は十二支の筆頭で、賢く機知に富んだ性格を持ちます。新しい環境への適応が素早く、観察力が鋭いです。チャンスを捉える能力が高く、実用的な思考の持ち主です。', strengths: '賢さ、適応力、社交性、実用的思考', weaknesses: '時に自己中心的、小心さ、投機的傾向', compatible: '丑（牛）、辰（龍）', careers: 'ビジネス、金融、ジャーナリズム、政治' },
    { traits: ['誠実で勤勉', '強い意志と忍耐力', '信頼できる', '保守的で伝統的'], personality: '丑（うし）は誠実で勤勉な性格として知られています。一度引き受けた仕事は責任感を持って最後までやり遂げます。言葉より行動で示すタイプで、約束をとても大切にします。', strengths: '誠実さ、信頼性、忍耐力、決断力', weaknesses: '頑固さ、変化への抵抗、融通が利かない', compatible: '子（鼠）、巳（蛇）', careers: '農業、建設、医療、教育、軍事' },
    { traits: ['勇敢で自信に満ちている', 'カリスマ的リーダーシップ', '競争心が強く野心的', '独立心旺盛'], personality: '寅（とら）は勇敢で情熱的な生まれながらのリーダーです。強い自信とカリスマ性で自然と注目を集めます。不正を見過ごせない正義感と、弱者を助けたい温かい心も持ち合わせています。', strengths: '勇気、カリスマ性、推進力、寛大さ', weaknesses: '衝動的、反骨精神、短気', compatible: '午（馬）、戌（犬）', careers: '軍人、消防士、起業家、政治家、スポーツ選手' },
    { traits: ['穏やかで優雅', '芸術的センスに優れる', '平和主義', '慎重で用心深い'], personality: '卯（うさぎ）は十二支の中で最も幸運な動物の一つとされています。穏やかで優雅な性格で周囲から愛されます。芸術的センスが抜群で、争いを嫌い平和な環境を好みます。', strengths: '優雅さ、外交術、芸術性、細やかさ', weaknesses: '過度に慎重、優柔不断、浅い人間関係', compatible: '未（羊）、亥（猪）', careers: '芸術、外交、医療、ファッション' },
    { traits: ['力強くカリスマ溢れる', '自信に満ちて情熱的', '成功志向', '創造的で知的'], personality: '辰（たつ）は十二支の中で唯一の神話上の動物で、最も強大なエネルギーを持ちます。生まれながらのリーダーシップとカリスマ性でどこでも目立ち、成功への熱望が尽きません。独立心が強く、自分流を貫きます。', strengths: 'リーダーシップ、情熱、創造性、自信', weaknesses: '傲慢になり得る、完璧主義、頑固さ', compatible: '子（鼠）、申（猿）', careers: 'CEO、芸術家、政治家、建築家' },
    { traits: ['知恵があり直感的', '慎重で思慮深い', '優雅で魅力的', '哲学的な思考'], personality: '巳（へび）は知恵と直感に優れた干支です。深く考え慎重に行動し、直感で状況を把握する能力があります。優雅で神秘的な魅力が人を惹きつけます。', strengths: '知恵、直感力、優雅さ、分析力', weaknesses: '疑い深い、怠けることがある、独占欲', compatible: '丑（牛）、酉（鶏）', careers: '哲学者、作家、心理学者、教師、占星術師' },
    { traits: ['活動的で自由奔放', '情熱的でエネルギッシュ', '独立的で旅を愛する', '表現力豊か'], personality: '午（うま）は自由で活動的な精神を持つ干支です。広大な草原を駆ける馬のように、自由と独立を渇望します。情熱的でエネルギー旺盛で、新しい環境や経験を楽しみます。', strengths: '活動力、自由な精神、表現力、独立性', weaknesses: '忍耐力不足、自己中心的になり得る、決断が苦手', compatible: '寅（虎）、未（羊）', careers: 'スポーツ選手、旅行家、セールスマン、ジャーナリスト' },
    { traits: ['創造的で芸術的', '穏やかで親切', '共感力に優れる', 'ロマンチック'], personality: '未（ひつじ）は穏やかで芸術的な感性を持つ干支です。創造的な才能と美的センスが抜群で、美しいものを作り楽しむことが好きです。他者への深い共感と理解心を持ちます。', strengths: '創造性、穏やかさ、共感力、芸術性', weaknesses: '依存しすぎる傾向、優柔不断、心配性', compatible: '卯（兎）、亥（猪）', careers: '芸術家、音楽家、デザイナー、カウンセラー' },
    { traits: ['賢くて機知に富む', '好奇心旺盛でいたずら好き', '習得が早い', '創造的問題解決'], personality: '申（さる）は十二支の中で最も賢く機知に富む干支です。素早い思考力と優れた問題解決能力を持ち、新しいことを学ぶのが早いです。ユーモアセンスが抜群で、どんな状況でもポジティブな面を見つけます。', strengths: '知性、機知、適応力、問題解決能力', weaknesses: '無責任になり得る、規律が苦手、不誠実になり得る', compatible: '辰（龍）、子（鼠）', careers: '科学者、エンジニア、作家、俳優、外交官' },
    { traits: ['勤勉で几帳面', '率直で自信がある', '完璧主義の傾向', '観察力が鋭い'], personality: '酉（とり）は勤勉で几帳面な性格として知られています。非常に細かく丁寧で、任された仕事を完璧にこなしたいという完璧主義があります。率直で直接的なコミュニケーションを好み、高い自尊心を持ちます。', strengths: '勤勉さ、几帳面さ、率直さ、自信', weaknesses: '批判的、完璧主義によるストレス、過信', compatible: '丑（牛）、巳（蛇）', careers: '軍人、外科医、歯科医、シェフ、俳優' },
    { traits: ['忠実で誠実', '公正で義理堅い', '保護本能が強い', '献身的'], personality: '戌（いぬ）は忠誠心と誠実さを最も大切にする干支です。一度信頼を置いた人には最後まで寄り添い、不正を見ると我慢できない強い正義感を持ちます。大切な人を守ろうとする本能が強いです。', strengths: '忠誠心、誠実さ、正義感、信頼性', weaknesses: '心配症、過度に批判的、頑固さ', compatible: '寅（虎）、午（馬）', careers: '警察官、社会福祉士、軍人、教師、裁判官' },
    { traits: ['穏やかで寛大', '誠実で純真', '楽しみを追求', '決断力がある'], personality: '亥（いのしし）は純真で寛大な心を持つ干支です。他者への強い信頼と楽観的な世界観を持ち、人生の喜びを十分に享受することを信じています。誠実で責任感があり、引き受けたことは最後までやり遂げます。', strengths: '寛大さ、誠実さ、楽観性、純真さ', weaknesses: '信じすぎる、物質的な誘惑、頑固さ', compatible: '卯（兎）、未（羊）', careers: '医師、研究者、エンターテイナー、サービス業' },
  ],
};
