import type { Lang } from './i18n';

export interface ZodiacEntry {
  traits: string[];
  personality: string;
  love: string;
  money: string;
  compatible: string;
  lucky: string;
}

export const ZODIAC_CONTENT: Record<Lang, ZodiacEntry[]> = {
  ko: [
    { traits: ['용감하고 도전적', '행동력이 뛰어남', '열정적이고 에너지 넘침', '리더십이 강함'], personality: '양자리는 황도대의 첫 번째 별자리로, 활동적이고 진취적인 성격을 가집니다. 새로운 일을 시작하는 데 두려움이 없으며, 목표가 생기면 거침없이 달려갑니다. 때로는 성급하거나 무모해 보일 수 있지만, 그 뒤에는 진심 어린 열정이 있습니다.', love: '연애에서 적극적으로 먼저 다가가는 타입입니다. 상대에 대한 강한 열정을 보이지만, 권태기가 빨리 찾아올 수 있어 새로운 자극이 필요합니다.', money: '금전적으로는 충동적인 소비를 하는 경향이 있습니다. 큰 목표를 위해 과감하게 투자하기도 하며, 사업적 추진력이 뛰어납니다.', compatible: '사자자리, 사수자리', lucky: '빨간색, 화요일, 숫자 9' },
    { traits: ['안정적이고 신중함', '인내심이 강함', '실용적이고 현실적', '감각적이고 풍요 추구'], personality: '황소자리는 현실적이고 안정을 중시하는 별자리입니다. 급격한 변화보다는 천천히 꾸준히 나아가는 것을 선호합니다. 물질적인 편안함과 아름다운 것에 대한 감각이 뛰어나며, 한 번 결심한 일은 끝까지 해냅니다.', love: '연애에서는 신중하고 안정적인 관계를 원합니다. 처음에는 쉽게 마음을 열지 않지만, 한 번 신뢰가 쌓이면 매우 헌신적인 파트너가 됩니다.', money: '재정적으로 매우 보수적이고 저축을 중시합니다. 충동구매보다는 가치 있는 것에 투자하며, 장기적인 재무 계획을 세우는 데 능합니다.', compatible: '처녀자리, 염소자리', lucky: '초록색, 금요일, 숫자 6' },
    { traits: ['호기심 많고 다재다능', '말재주가 뛰어남', '사교적이고 친절함', '빠른 사고력'], personality: '쌍둥이자리는 두 가지 면을 동시에 가진 이중적인 별자리입니다. 지적 호기심이 왕성하고 다양한 분야에 관심이 많습니다. 뛰어난 언어 능력과 소통 능력으로 어디서든 환영받으며, 새로운 정보와 아이디어를 흡수하는 데 탁월합니다.', love: '연애에서 지적 자극과 대화를 매우 중시합니다. 재미있고 활기찬 관계를 원하며, 지루함을 잘 견디지 못합니다. 다양한 주제로 깊은 대화를 나눌 수 있는 파트너를 선호합니다.', money: '다양한 분야의 수입원을 갖는 경향이 있습니다. 아이디어를 통해 수익을 창출하는 데 능하지만, 집중력 부족으로 기회를 놓치는 경우도 있습니다.', compatible: '천칭자리, 물병자리', lucky: '노란색, 수요일, 숫자 5' },
    { traits: ['감성적이고 공감 능력 탁월', '가정과 가족을 소중히 여김', '직관력이 뛰어남', '보호 본능이 강함'], personality: '게자리는 감성적이고 직관이 뛰어난 별자리입니다. 달의 지배를 받아 감정의 기복이 있을 수 있지만, 그만큼 타인의 감정을 잘 이해하고 공감합니다. 가족과 집에 대한 애착이 강하며, 소중한 사람들을 위해 헌신합니다.', love: '연애에서 깊고 진실한 감정적 유대를 원합니다. 상대방을 세심하게 배려하고 돌보는 타입이지만, 감정적인 상처를 받으면 회복에 시간이 걸립니다.', money: '경제적 안정에 대한 강한 욕구가 있습니다. 저축과 부동산 투자에 관심이 많으며, 가족을 위한 재정적 기반을 마련하는 데 집중합니다.', compatible: '전갈자리, 물고기자리', lucky: '은색, 월요일, 숫자 2' },
    { traits: ['카리스마 넘치는 리더', '창의적이고 표현력이 강함', '관대하고 따뜻한 마음', '자존감이 높음'], personality: '사자자리는 태양의 에너지를 받아 당당하고 빛나는 존재감을 가집니다. 타고난 리더십으로 집단에서 자연스럽게 중심이 되며, 관대하고 따뜻한 마음으로 주변 사람들에게 사랑받습니다. 인정받고 주목받는 것을 즐깁니다.', love: '연애에서 열정적이고 로맨틱한 면을 보입니다. 상대방이 자신을 특별하게 여겨주기를 원하며, 화려하고 드라마틱한 사랑을 추구합니다.', money: '큰 그림을 보는 안목이 있어 사업적 성공 가능성이 높습니다. 명성과 사회적 지위를 위해 투자하는 경향이 있으며, 과한 소비에 주의가 필요합니다.', compatible: '양자리, 사수자리', lucky: '금색, 일요일, 숫자 1' },
    { traits: ['분석적이고 꼼꼼함', '실용적이고 서비스 정신 강함', '완벽주의 성향', '건강과 일상 루틴 중시'], personality: '처녀자리는 세밀하고 분석적인 사고를 가진 별자리입니다. 완벽을 추구하는 성향으로 맡은 일은 철저하게 해냅니다. 실용적이고 논리적인 접근을 선호하며, 다른 사람을 돕는 것에서 보람을 느낍니다.', love: '연애에서 처음에는 신중하고 조심스럽습니다. 완벽한 파트너를 찾는 경향이 있어 쉽게 만족하지 않지만, 한 번 사랑에 빠지면 헌신적이고 세심한 파트너가 됩니다.', money: '재정 관리에 뛰어난 별자리입니다. 꼼꼼하게 가계부를 작성하고, 불필요한 지출을 최소화합니다. 안정적인 저축과 투자를 선호합니다.', compatible: '황소자리, 염소자리', lucky: '베이지색, 수요일, 숫자 6' },
    { traits: ['균형과 공정함 추구', '사교적이고 외교적', '아름다움에 대한 감각', '협력적이고 조화 중시'], personality: '천칭자리는 균형과 조화를 추구하는 별자리입니다. 타고난 외교관으로 갈등을 중재하고 공정한 해결책을 찾는 데 탁월합니다. 아름다운 것에 끌리며, 예술과 문화에 조예가 깊습니다.', love: '연애에서 가장 낭만적인 별자리 중 하나입니다. 아름다운 관계를 원하며, 파트너와의 균형 잡힌 관계를 중시합니다. 결정을 내리는 것이 어려워 우유부단해 보일 수 있습니다.', money: '재정적 결정에서 균형을 찾으려 합니다. 충동적이지 않으나 미적 만족을 위한 지출은 아끼지 않습니다. 파트너와 함께하는 재무 계획을 선호합니다.', compatible: '쌍둥이자리, 물병자리', lucky: '분홍색, 금요일, 숫자 7' },
    { traits: ['강렬하고 신비로운 매력', '직관력과 통찰력이 뛰어남', '집중력과 의지력이 강함', '변화와 재생의 에너지'], personality: '전갈자리는 황도대에서 가장 강렬하고 신비로운 별자리입니다. 깊은 내면의 세계를 가지고 있으며, 진실을 꿰뚫어 보는 직관력이 있습니다. 한 번 목표를 정하면 어떠한 역경도 이겨내는 불굴의 의지를 가집니다.', love: '연애에서 깊고 강렬한 감정적 연결을 추구합니다. 표면적인 관계보다 영혼까지 닿는 깊은 유대를 원하며, 질투심과 소유욕이 강한 편입니다.', money: '재정적으로 전략적이고 통찰력이 있습니다. 투자에서 남들이 보지 못하는 기회를 포착하는 능력이 있으며, 위기 상황에서도 냉정하게 대처합니다.', compatible: '게자리, 물고기자리', lucky: '검은색, 화요일, 숫자 8' },
    { traits: ['낙관적이고 모험을 즐김', '자유와 독립을 소중히 여김', '철학적 사고와 지적 탐구', '유머 감각이 풍부함'], personality: '사수자리는 자유롭고 낙관적인 영혼의 별자리입니다. 세상을 탐험하고 다양한 문화와 철학을 배우는 것을 즐깁니다. 경계와 제약을 싫어하며, 항상 새로운 지평을 향해 나아가는 진취적인 성격입니다.', love: '연애에서 자유롭고 부담 없는 관계를 원합니다. 상대방의 독립성을 존중하고, 함께 모험을 즐길 수 있는 파트너를 선호합니다. 장기적 헌신이 어려울 수 있습니다.', money: '재정적으로 낙관적인 편이라 과도하게 낙관적인 투자를 할 수 있습니다. 그러나 운이 따르는 경우가 많으며, 예상치 못한 기회를 통해 수익을 얻기도 합니다.', compatible: '양자리, 사자자리', lucky: '보라색, 목요일, 숫자 3' },
    { traits: ['성실하고 목표 지향적', '인내심과 책임감이 강함', '현실적이고 실용적', '장기적 계획과 전략 수립'], personality: '염소자리는 황도대에서 가장 성실하고 야망 있는 별자리입니다. 높은 목표를 향해 천천히 하지만 확실하게 나아가며, 어떠한 어려움도 포기하지 않습니다. 사회적 지위와 성공에 대한 강한 욕구가 있습니다.', love: '연애에서 신중하고 진지한 접근을 합니다. 가벼운 만남보다는 진지하고 안정적인 관계를 원하며, 파트너에게 신뢰와 안정을 제공하는 믿음직한 동반자가 됩니다.', money: '재정 관리에서 최강자입니다. 장기적인 재무 목표를 세우고 체계적으로 저축하며, 안정적인 투자를 선호합니다. 경제적 성공 가능성이 높습니다.', compatible: '황소자리, 처녀자리', lucky: '검은색, 토요일, 숫자 10' },
    { traits: ['독창적이고 혁신적', '인도주의적 가치 추구', '독립적이고 자유로운 사고', '미래 지향적 비전'], personality: '물병자리는 황도대에서 가장 독창적이고 미래 지향적인 별자리입니다. 기존의 틀을 깨고 새로운 아이디어와 혁신을 추구합니다. 인류 전체의 진보와 발전에 관심이 많으며, 개인보다 사회 전체의 이익을 위해 생각합니다.', love: '연애에서 친구 같은 편안한 관계를 원합니다. 상대방의 개성과 독립성을 존중하며, 지적으로 자극이 되는 파트너를 선호합니다. 감정 표현이 서투를 수 있습니다.', money: '재정적으로 독특한 접근을 합니다. 혁신적인 투자 기회에 관심이 많으며, 기술과 미래 산업 분야에서 기회를 찾습니다. 때로는 비현실적인 재정 계획을 세울 수 있습니다.', compatible: '쌍둥이자리, 천칭자리', lucky: '하늘색, 토요일, 숫자 4' },
    { traits: ['감성적이고 공감 능력 풍부', '상상력과 창의성이 넘침', '영적이고 직관적', '동정심이 강하고 희생적'], personality: '물고기자리는 황도대의 마지막이자 모든 별자리의 에너지를 품은 별자리입니다. 깊은 감수성과 풍부한 상상력을 가지며, 예술적 재능이 뛰어납니다. 타인의 감정을 자신의 것처럼 느끼는 강한 공감 능력을 가지고 있습니다.', love: '연애에서 이상적이고 로맨틱한 사랑을 꿈꿉니다. 영적인 연결과 깊은 감정적 유대를 원하며, 상대방을 위해 헌신적으로 희생합니다. 현실과 이상의 차이로 실망하지 않도록 주의가 필요합니다.', money: '재정적으로 꼼꼼하게 관리하는 것이 어려울 수 있습니다. 직관적인 결정으로 예상치 못한 행운을 얻기도 하지만, 체계적인 재무 계획이 필요합니다.', compatible: '게자리, 전갈자리', lucky: '보라색, 목요일, 숫자 7' },
  ],

  en: [
    { traits: ['Brave and daring', 'Takes action quickly', 'Passionate and energetic', 'Natural leader'], personality: 'Aries is the first sign of the zodiac, known for an active and pioneering spirit. They charge toward goals without hesitation. While they can seem impulsive or reckless, genuine passion drives everything they do.', love: 'In love, Aries boldly makes the first move. They show intense passion, but boredom can set in quickly — they need constant excitement and new experiences.', money: 'Financially, Aries tends toward impulsive spending. They invest boldly to achieve big goals, and their entrepreneurial drive is second to none.', compatible: 'Leo, Sagittarius', lucky: 'Red, Tuesday, Number 9' },
    { traits: ['Stable and careful', 'Patient and persistent', 'Practical and realistic', 'Sensual, loves comfort'], personality: 'Taurus is a grounded, stability-loving sign. They prefer slow, steady progress over sudden change. They have an excellent eye for beauty and material comfort, and once committed, they see things through to the end.', love: 'In love, Taurus seeks a steady, secure relationship. They take time to open up, but once trust is established, they become an incredibly devoted partner.', money: 'Financially very conservative, Taurus prioritizes saving. They invest in quality over impulse buys and excel at long-term financial planning.', compatible: 'Virgo, Capricorn', lucky: 'Green, Friday, Number 6' },
    { traits: ['Curious and versatile', 'Gifted communicator', 'Sociable and friendly', 'Quick thinker'], personality: 'Gemini is a dual sign with two distinct sides. Their intellectual curiosity spans many fields, and their exceptional communication skills make them welcome everywhere. They absorb new information and ideas with remarkable speed.', love: 'In love, Gemini values intellectual stimulation and deep conversation. They want fun, lively relationships and struggle with boredom. They prefer a partner who can discuss a wide range of topics.', money: 'Gemini tends to have multiple income streams. They are skilled at generating revenue through ideas, though lack of focus can sometimes cause them to miss opportunities.', compatible: 'Libra, Aquarius', lucky: 'Yellow, Wednesday, Number 5' },
    { traits: ['Emotional and deeply empathetic', 'Family-oriented', 'Highly intuitive', 'Protective instinct'], personality: 'Cancer is an emotional, deeply intuitive sign. Ruled by the Moon, they can be moody, but this also gives them an extraordinary ability to understand and empathize with others. They are fiercely devoted to family and home.', love: 'In love, Cancer craves a deep, genuine emotional bond. They are nurturing and attentive, but emotional wounds take time to heal.', money: 'Cancer has a strong desire for financial security. They are drawn to savings and real estate, focusing on building a solid foundation for their family.', compatible: 'Scorpio, Pisces', lucky: 'Silver, Monday, Number 2' },
    { traits: ['Charismatic leader', 'Creative and expressive', 'Generous and warm-hearted', 'High self-esteem'], personality: 'Leo radiates confidence and a commanding presence, powered by the Sun. A natural-born leader, they gravitate to the center of any group. Their generosity and warmth make them beloved by those around them.', love: 'In love, Leo is passionate and deeply romantic. They want to be seen as special by their partner and are drawn to grand, dramatic expressions of love.', money: 'Leo has the vision to see the big picture, giving them strong entrepreneurial potential. They invest in prestige and social standing, but need to watch out for overspending.', compatible: 'Aries, Sagittarius', lucky: 'Gold, Sunday, Number 1' },
    { traits: ['Analytical and detail-oriented', 'Practical, strong service ethic', 'Perfectionist tendencies', 'Values health and routine'], personality: 'Virgo is a meticulous, analytical thinker. Their perfectionist nature means they handle tasks thoroughly and completely. They prefer practical and logical approaches and find deep satisfaction in helping others.', love: 'In love, Virgo starts out cautious and reserved. They have high standards and rarely settle, but once they fall in love, they become a devoted, attentive partner.', money: 'Virgo is one of the best signs at managing finances. They track expenses carefully, minimize waste, and prefer stable savings and investments.', compatible: 'Taurus, Capricorn', lucky: 'Beige, Wednesday, Number 6' },
    { traits: ['Seeks balance and fairness', 'Sociable and diplomatic', 'Refined aesthetic sense', 'Cooperative and harmonious'], personality: 'Libra seeks balance and harmony above all. A natural diplomat, they excel at mediating conflict and finding fair solutions. They are drawn to beauty and have a deep appreciation for art and culture.', love: 'Libra is one of the most romantic signs. They want a beautiful relationship and prioritize balance with their partner. Their need to weigh options can make them seem indecisive.', money: 'Libra seeks balance in financial decisions too. Not impulsive, but they never skimp on things that bring aesthetic pleasure. They prefer managing finances with a partner.', compatible: 'Gemini, Aquarius', lucky: 'Pink, Friday, Number 7' },
    { traits: ['Intense and mysterious', 'Powerful intuition and insight', 'Strong focus and willpower', 'Energy of transformation'], personality: 'Scorpio is the most intense and mysterious sign of the zodiac. They have a rich inner world and a penetrating intuition that sees through to the truth. Once they set a goal, they overcome any obstacle with iron will.', love: 'In love, Scorpio seeks deep, intense emotional connections. They crave a soulful bond beyond the surface, and can be quite jealous and possessive.', money: 'Financially, Scorpio is strategic and insightful. They spot opportunities others miss and stay cool-headed even in a crisis.', compatible: 'Cancer, Pisces', lucky: 'Black, Tuesday, Number 8' },
    { traits: ['Optimistic and adventurous', 'Values freedom and independence', 'Philosophical and intellectually curious', 'Great sense of humor'], personality: 'Sagittarius is a free-spirited, optimistic soul. They love exploring the world and learning from different cultures and philosophies. They dislike limits and restrictions, always pushing toward new horizons with a pioneering spirit.', love: 'In love, Sagittarius wants a free, pressure-free relationship. They respect their partner\'s independence and prefer someone who shares their love of adventure. Long-term commitment can be a challenge.', money: 'Financially optimistic, Sagittarius can make overly rosy investment choices. However, luck often follows them, and unexpected opportunities frequently lead to gains.', compatible: 'Aries, Leo', lucky: 'Purple, Thursday, Number 3' },
    { traits: ['Diligent and goal-oriented', 'Patient and responsible', 'Realistic and practical', 'Plans for the long term'], personality: 'Capricorn is the most diligent and ambitious sign of the zodiac. They move slowly but surely toward their high goals, never giving up. They have an intense drive for social status and success.', love: 'In love, Capricorn takes a careful, serious approach. They prefer deep, stable relationships over casual encounters, and become a reliable, dependable partner.', money: 'Capricorn is the top financial manager of the zodiac. They set long-term financial goals, save systematically, and favor stable investments. Economic success is highly likely.', compatible: 'Taurus, Virgo', lucky: 'Black, Saturday, Number 10' },
    { traits: ['Original and innovative', 'Humanitarian values', 'Independent, free thinker', 'Future-oriented visionary'], personality: 'Aquarius is the most original and forward-thinking sign of the zodiac. They break conventional molds and constantly seek new ideas and innovation. They care deeply about human progress and think about the greater good over personal gain.', love: 'In love, Aquarius wants a comfortable, friendship-like relationship. They respect their partner\'s individuality and independence, preferring someone who provides intellectual stimulation. Emotional expression can be difficult for them.', money: 'Financially, Aquarius takes a unique approach. They are drawn to innovative investment opportunities and seek chances in technology and future industries. Their financial plans can sometimes be unrealistic.', compatible: 'Gemini, Libra', lucky: 'Sky blue, Saturday, Number 4' },
    { traits: ['Emotional and deeply empathetic', 'Boundless imagination and creativity', 'Spiritual and intuitive', 'Compassionate and self-sacrificing'], personality: 'Pisces is the last sign of the zodiac, holding the energy of all other signs within it. They have deep sensitivity, rich imagination, and remarkable artistic talent. Their powerful empathy means they feel others\' emotions as their own.', love: 'In love, Pisces dreams of idealized, romantic love. They seek a spiritual connection and a deep emotional bond, and will sacrifice much for their partner. They must guard against disappointment when reality falls short of the ideal.', money: 'Managing finances carefully can be a challenge for Pisces. Intuitive decisions sometimes lead to unexpected windfalls, but a more systematic financial plan is beneficial.', compatible: 'Cancer, Scorpio', lucky: 'Purple, Thursday, Number 7' },
  ],

  zh: [
    { traits: ['勇敢好挑战', '行动力超强', '热情活力充沛', '领导力强'], personality: '白羊座是黄道十二宫的第一个星座，性格积极进取。他们勇于开始新事物，一旦设定目标就全力以赴。虽然有时看似冲动莽撞，但背后有着真诚的热情。', love: '在恋爱中，白羊座勇于主动出击。对伴侣展现强烈热情，但容易产生倦怠感，需要持续的新鲜感刺激。', money: '在财务上容易冲动消费。为了大目标敢于大胆投资，创业推进力出众。', compatible: '狮子座、射手座', lucky: '红色、周二、数字9' },
    { traits: ['稳重谨慎', '耐心坚韧', '务实现实', '感官享受，追求富足'], personality: '金牛座是重视现实与稳定的星座。相比急剧变化，更偏好缓慢稳步前进。对物质享受和美好事物有着敏锐的感知力，一旦下定决心就会坚持到底。', love: '在恋爱中追求稳定安全的关系。起初不易敞开心扉，但一旦建立信任，就会成为极为忠诚的伴侣。', money: '财务观念非常保守，注重储蓄。比起冲动消费，更倾向于投资有价值的事物，擅长制定长期财务计划。', compatible: '处女座、摩羯座', lucky: '绿色、周五、数字6' },
    { traits: ['好奇心强，多才多艺', '口才出众', '善于社交，友善亲切', '思维敏捷'], personality: '双子座是同时拥有两面性的星座。求知欲旺盛，兴趣广泛。凭借出色的语言能力和沟通技巧，在任何场合都受欢迎，吸收新信息和想法的速度极快。', love: '在恋爱中非常重视智识上的刺激与深度交流。渴望有趣活跃的关系，不耐无聊。喜欢能就各种话题进行深度交谈的伴侣。', money: '倾向于拥有多种收入来源。善于通过创意赚钱，但有时因注意力分散而错失良机。', compatible: '天秤座、水瓶座', lucky: '黄色、周三、数字5' },
    { traits: ['感性，共情力极强', '重视家庭', '直觉敏锐', '保护欲强'], personality: '巨蟹座是感性而直觉出众的星座。受月亮支配，情绪有起伏，但也因此能深刻理解和共情他人。对家人和家的依恋很深，愿意为所爱之人全力付出。', love: '在恋爱中渴望深刻真诚的情感纽带。对伴侣细心关怀，但一旦受到情感伤害，需要较长时间才能恢复。', money: '对经济稳定有强烈渴望。热衷于储蓄和不动产投资，专注于为家人打下坚实的财务基础。', compatible: '天蝎座、双鱼座', lucky: '银色、周一、数字2' },
    { traits: ['魅力十足的领导者', '富有创意，表达力强', '慷慨热情', '自尊心高'], personality: '狮子座受太阳能量加持，气场十足，光彩照人。天生的领导力使其自然成为群体中心，慷慨温暖的心让周围的人都喜爱他们。享受被认可和受到关注。', love: '在恋爱中热情浪漫。希望被伴侣视为特别的存在，追求华丽戏剧性的爱情。', money: '具有纵观全局的眼光，创业成功潜力高。倾向于为名声和社会地位投资，需注意过度消费。', compatible: '白羊座、射手座', lucky: '金色、周日、数字1' },
    { traits: ['分析力强，细心周到', '务实，服务精神强', '完美主义倾向', '注重健康与日常规律'], personality: '处女座是思维缜密、善于分析的星座。追求完美的倾向使其处理事务极为彻底。偏好务实和逻辑性的方法，从帮助他人中获得成就感。', love: '在恋爱初期谨慎小心。有寻找完美伴侣的倾向，不易满足，但一旦坠入爱河，就会成为忠诚细心的伴侣。', money: '财务管理能力出众。认真记录收支，将不必要的开销降至最低，偏好稳定的储蓄与投资。', compatible: '金牛座、摩羯座', lucky: '米色、周三、数字6' },
    { traits: ['追求平衡与公正', '善于社交，外交手腕强', '审美感强', '合作共赢，注重和谐'], personality: '天秤座是追求平衡与和谐的星座。天生的外交家，擅长调解矛盾，寻找公平的解决方案。被美好事物所吸引，在艺术和文化方面造诣颇深。', love: '天秤座是最浪漫的星座之一。渴望美好的关系，重视与伴侣之间的平衡。因过于权衡利弊，有时显得优柔寡断。', money: '在财务决策上力求平衡。不冲动，但在能带来美学满足的事物上毫不吝啬。偏好与伴侣共同规划财务。', compatible: '双子座、水瓶座', lucky: '粉色、周五、数字7' },
    { traits: ['强烈而神秘的魅力', '直觉与洞察力出众', '专注力与意志力强', '蜕变与重生的能量'], personality: '天蝎座是黄道中最强烈、最神秘的星座。拥有深邃的内心世界，以及能洞穿真相的直觉。一旦设定目标，无论任何逆境都能以不屈的意志克服。', love: '在恋爱中追求深刻而强烈的情感连接。渴望灵魂层面的深度纽带，嫉妒心和占有欲较强。', money: '在财务上极具战略眼光和洞察力。能捕捉他人看不见的投资机遇，危机时刻也能保持冷静应对。', compatible: '巨蟹座、双鱼座', lucky: '黑色、周二、数字8' },
    { traits: ['乐观，热爱冒险', '珍视自由与独立', '哲学思维，热衷智识探索', '幽默感十足'], personality: '射手座是自由奔放、乐观向上的星座。热爱探索世界，学习不同文化与哲学。讨厌约束，始终向着新的地平线进取，充满开拓精神。', love: '在恋爱中渴望自由无压力的关系。尊重伴侣的独立性，喜欢能一同冒险的伴侣。长期承诺对他们来说可能是个挑战。', money: '财务上过于乐观，有时会做出过于冒进的投资。但幸运总是相随，常能通过意外机遇获利。', compatible: '白羊座、狮子座', lucky: '紫色、周四、数字3' },
    { traits: ['勤奋，目标导向', '耐心与责任感强', '现实务实', '擅长长期规划与战略'], personality: '摩羯座是黄道中最勤奋、最有抱负的星座。朝着高远目标缓慢但坚定地前行，从不轻言放弃。对社会地位和成功有着强烈的渴望。', love: '在恋爱中态度谨慎认真。比起随意的约会，更渴望严肃稳定的关系，是能给伴侣带来信任与安全感的可靠伴侣。', money: '摩羯座是财务管理的顶尖高手。设定长期财务目标，系统性储蓄，偏好稳健投资，经济成功的可能性极高。', compatible: '金牛座、处女座', lucky: '黑色、周六、数字10' },
    { traits: ['独创性强，富有革新精神', '追求人道主义价值', '独立，思维自由', '面向未来的远见者'], personality: '水瓶座是黄道中最具独创性和前瞻性的星座。打破常规，不断追求新思想与创新。对人类整体的进步与发展高度关注，从社会整体利益出发思考问题。', love: '在恋爱中渴望如朋友般轻松自在的关系。尊重伴侣的个性与独立性，偏好能提供智识刺激的伴侣。情感表达有时略显笨拙。', money: '在财务上有独到见解。热衷于创新型投资机遇，在科技和未来产业领域寻找机会。有时会制定不切实际的财务计划。', compatible: '双子座、天秤座', lucky: '天蓝色、周六、数字4' },
    { traits: ['感性，共情能力丰富', '想象力与创造力无限', '灵性而直觉强', '富有同情心，甘于奉献'], personality: '双鱼座是黄道的最后一个星座，蕴含所有星座的能量。拥有深刻的感受力和丰富的想象力，艺术才华出众。强大的共情能力使他们能感同身受地理解他人。', love: '在恋爱中梦想理想化的浪漫之爱。渴望灵性的连接与深刻的情感纽带，愿意为伴侣无私奉献。需注意不要因理想与现实的差距而感到失望。', money: '精细管理财务对双鱼座来说可能比较困难。凭直觉做出的决定有时会带来意外之财，但仍需系统性的财务规划。', compatible: '巨蟹座、天蝎座', lucky: '紫色、周四、数字7' },
  ],

  ja: [
    { traits: ['勇敢で挑戦的', '行動力が抜群', '情熱的でエネルギッシュ', 'リーダーシップが強い'], personality: '牡羊座は黄道十二宮の最初の星座で、活動的で進取的な性格を持ちます。新しいことを始めることへの恐れがなく、目標ができれば一直線に突き進みます。時に性急や無謀に見えることもありますが、その裏には真摯な情熱があります。', love: '恋愛では積極的に自ら動くタイプです。相手への強い情熱を見せますが、倦怠期が早く訪れやすく、常に新しい刺激が必要です。', money: '金銭的には衝動買いをしやすい傾向があります。大きな目標のために大胆に投資することもあり、ビジネスの推進力は随一です。', compatible: '獅子座、射手座', lucky: '赤、火曜日、数字9' },
    { traits: ['安定していて慎重', '忍耐力が強い', '実用的で現実的', '感覚的で豊かさを追求'], personality: '牡牛座は現実的で安定を重んじる星座です。急激な変化よりも、ゆっくり着実に進むことを好みます。物質的な快適さや美しいものへの感覚が鋭く、一度決めたことは最後までやり遂げます。', love: '恋愛では慎重で安定した関係を求めます。最初はなかなか心を開きませんが、信頼関係が築かれると非常に献身的なパートナーになります。', money: '財政的にとても保守的で、貯蓄を重視します。衝動買いより価値あるものへの投資を好み、長期的な財務計画を立てるのが得意です。', compatible: '乙女座、山羊座', lucky: '緑色、金曜日、数字6' },
    { traits: ['好奇心旺盛で多才', '話術に優れる', '社交的で親切', '素早い思考力'], personality: '双子座は二つの顔を持つ二面性の星座です。知的好奇心が旺盛で様々な分野に興味を持ちます。優れた言語能力とコミュニケーション能力でどこでも歓迎され、新しい情報やアイデアを吸収するのが得意です。', love: '恋愛では知的刺激と会話をとても重視します。楽しくて活発な関係を求め、退屈に耐えられません。様々なテーマで深い会話ができるパートナーを好みます。', money: '様々な分野の収入源を持つ傾向があります。アイデアで収益を生み出すのが得意ですが、集中力不足でチャンスを逃すこともあります。', compatible: '天秤座、水瓶座', lucky: '黄色、水曜日、数字5' },
    { traits: ['感受性豊かで共感力抜群', '家庭・家族を大切にする', '直感力が優れる', '保護本能が強い'], personality: '蟹座は感情豊かで直感の鋭い星座です。月の支配を受け感情の起伏はありますが、それだけ他者の気持ちをよく理解し共感できます。家族や家への愛着が強く、大切な人のために献身します。', love: '恋愛では深く真実の感情的なつながりを求めます。相手を細やかに気遣うタイプですが、感情的な傷を受けると回復に時間がかかります。', money: '経済的安定に対する強い欲求があります。貯蓄や不動産投資に関心が高く、家族のための財政的基盤づくりに集中します。', compatible: '蠍座、魚座', lucky: '銀色、月曜日、数字2' },
    { traits: ['カリスマ溢れるリーダー', '創造的で表現力が強い', '寛大で温かい心', '自尊心が高い'], personality: '獅子座は太陽のエネルギーを受け、堂々とした輝く存在感を持ちます。生まれ持ったリーダーシップで自然と集団の中心になり、寛大で温かい心で周りから愛されます。認められ注目されることを楽しみます。', love: '恋愛では情熱的でロマンチックな一面を見せます。相手に自分を特別に思ってほしいと願い、華やかでドラマチックな愛を求めます。', money: '大局を見る眼があり、ビジネスでの成功可能性が高いです。名声と社会的地位のために投資する傾向があり、過度な出費には注意が必要です。', compatible: '牡羊座、射手座', lucky: '金色、日曜日、数字1' },
    { traits: ['分析的で細やか', '実用的でサービス精神旺盛', '完璧主義な傾向', '健康と日常ルーティンを重視'], personality: '乙女座は緻密で分析的な思考を持つ星座です。完璧を追求する性質から、任された仕事は徹底してやり遂げます。実用的で論理的なアプローチを好み、人を助けることにやりがいを感じます。', love: '恋愛の最初は慎重で遠慮がちです。完璧なパートナーを求める傾向があり、なかなか満足しませんが、一度恋に落ちると献身的で細やかなパートナーになります。', money: '財務管理に優れた星座です。こまめに家計を記録し、無駄な支出を最小限に抑えます。安定した貯蓄と投資を好みます。', compatible: '牡牛座、山羊座', lucky: 'ベージュ色、水曜日、数字6' },
    { traits: ['均衡と公正さを追求', '社交的で外交的', '美への感覚', '協調的で調和を重視'], personality: '天秤座は均衡と調和を追求する星座です。生まれながらの外交官として、対立を仲裁し公正な解決策を見つけるのが得意です。美しいものに惹かれ、芸術と文化への造詣が深いです。', love: '天秤座は最もロマンチックな星座の一つです。美しい関係を求め、パートナーとのバランスのとれた関係を重視します。決断が難しく優柔不断に見えることもあります。', money: '財務上の決断でもバランスを求めます。衝動的ではありませんが、美的満足のための出費は惜しみません。パートナーと一緒に財務計画を立てることを好みます。', compatible: '双子座、水瓶座', lucky: 'ピンク色、金曜日、数字7' },
    { traits: ['強烈で謎めいた魅力', '直感力と洞察力に優れる', '集中力と意志力が強い', '変化と再生のエネルギー'], personality: '蠍座は黄道の中で最も強烈で神秘的な星座です。深い内面の世界を持ち、真実を見抜く直感力があります。一度目標を定めると、どんな逆境も乗り越える不屈の意志を持ちます。', love: '恋愛では深く強烈な感情的つながりを求めます。表面的な関係よりも魂が触れ合う深い絆を求め、嫉妬心や独占欲が強い方です。', money: '財政的に戦略的で洞察力があります。他の人が見えない投資の機会を捉える能力があり、危機的状況でも冷静に対処します。', compatible: '蟹座、魚座', lucky: '黒色、火曜日、数字8' },
    { traits: ['楽観的で冒険を楽しむ', '自由と独立を大切にする', '哲学的思考と知的探求', 'ユーモアセンスが豊か'], personality: '射手座は自由で楽観的な魂の星座です。世界を探検し、様々な文化や哲学を学ぶことを楽しみます。制限や束縛を嫌い、常に新しい地平に向かって進む進取の精神を持ちます。', love: '恋愛では自由でプレッシャーのない関係を求めます。相手の独立性を尊重し、一緒に冒険を楽しめるパートナーを好みます。長期的なコミットメントが難しいこともあります。', money: '財政的に楽観的な分、過度に楽観的な投資をすることがあります。しかし運が伴うことが多く、思わぬチャンスで利益を得ることもよくあります。', compatible: '牡羊座、獅子座', lucky: '紫色、木曜日、数字3' },
    { traits: ['誠実で目標指向', '忍耐力と責任感が強い', '現実的で実用的', '長期的な計画と戦略を立てる'], personality: '山羊座は黄道の中で最も誠実で野心的な星座です。高い目標に向かってゆっくりでも確実に進み、どんな困難にも諦めません。社会的地位と成功への強い欲求があります。', love: '恋愛では慎重で真剣なアプローチをします。軽い出会いよりも真剣で安定した関係を求め、パートナーに信頼と安定を与える頼もしい伴侶となります。', money: '財務管理において最強の星座です。長期的な財務目標を設定し、計画的に貯蓄し、安定した投資を好みます。経済的成功の可能性が高いです。', compatible: '牡牛座、乙女座', lucky: '黒色、土曜日、数字10' },
    { traits: ['独創的で革新的', '人道主義的な価値を追求', '独立した自由な思考', '未来志向のビジョン'], personality: '水瓶座は黄道で最も独創的で未来志向の星座です。既存の枠を壊し、新しいアイデアと革新を追求します。人類全体の進歩と発展に関心が高く、個人よりも社会全体の利益のために考えます。', love: '恋愛では友達のような気楽な関係を求めます。相手の個性と独立性を尊重し、知的に刺激になるパートナーを好みます。感情表現が苦手なことがあります。', money: '財政的に独自のアプローチをします。革新的な投資機会に関心が高く、テクノロジーや将来産業の分野でチャンスを見つけます。時に非現実的な財務計画を立てることもあります。', compatible: '双子座、天秤座', lucky: '空色、土曜日、数字4' },
    { traits: ['感受性豊かで共感力が高い', '想像力と創造性があふれる', '霊的で直感的', '同情心が強く自己犠牲的'], personality: '魚座は黄道の最後の星座で、すべての星座のエネルギーを内包しています。深い感受性と豊かな想像力を持ち、芸術的才能が優れています。他者の感情を自分のものとして感じる強い共感力を持っています。', love: '恋愛では理想的でロマンチックな愛を夢見ます。精神的なつながりと深い感情的な絆を求め、相手のために献身的に犠牲を払います。現実と理想の差で失望しないように注意が必要です。', money: '財政を細かく管理することが難しいことがあります。直感的な決断で思わぬ幸運を得ることもありますが、体系的な財務計画が必要です。', compatible: '蟹座、蠍座', lucky: '紫色、木曜日、数字7' },
  ],
};
